# Site settings
title: The Banner Open
email: enquires@thebanneropen.com
description: > # this means to ignore newlines until "baseurl:"
  Clare's premier endurance golfing competition. 
  18 holes, teams of two. Best ball.
  10 cans to be consumed or shots deducted per can.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown